'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Listar() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listar", ReplyAction:="*")>  _
        Function ListarAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Agregar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Agregar( _
                    ByVal Ruc As String,  _
                    ByVal Nombre As String,  _
                    ByVal TipoDocumento As String,  _
                    ByVal Estado As String,  _
                    ByVal Condicion As String,  _
                    ByVal Direccion As String,  _
                    ByVal Ubigeo As String,  _
                    ByVal ViaTipo As String,  _
                    ByVal ViaNombre As String,  _
                    ByVal ZonaCodi As String,  _
                    ByVal ZonaTipo As String,  _
                    ByVal numero As String,  _
                    ByVal Interior As String,  _
                    ByVal Lote As String,  _
                    ByVal Dpto As String,  _
                    ByVal Manzana As String,  _
                    ByVal Kilometro As String,  _
                    ByVal Distrito As String,  _
                    ByVal Provincia As String,  _
                    ByVal Departamento As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Agregar", ReplyAction:="*")>  _
        Function AgregarAsync( _
                    ByVal Ruc As String,  _
                    ByVal Nombre As String,  _
                    ByVal TipoDocumento As String,  _
                    ByVal Estado As String,  _
                    ByVal Condicion As String,  _
                    ByVal Direccion As String,  _
                    ByVal Ubigeo As String,  _
                    ByVal ViaTipo As String,  _
                    ByVal ViaNombre As String,  _
                    ByVal ZonaCodi As String,  _
                    ByVal ZonaTipo As String,  _
                    ByVal numero As String,  _
                    ByVal Interior As String,  _
                    ByVal Lote As String,  _
                    ByVal Dpto As String,  _
                    ByVal Manzana As String,  _
                    ByVal Kilometro As String,  _
                    ByVal Distrito As String,  _
                    ByVal Provincia As String,  _
                    ByVal Departamento As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Buscar(ByVal texto As String, ByVal criterio As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar", ReplyAction:="*")>  _
        Function BuscarAsync(ByVal texto As String, ByVal criterio As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Listar() As System.Data.DataSet Implements ServiceReference1.WebService1Soap.Listar
            Return MyBase.Channel.Listar
        End Function
        
        Public Function ListarAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.WebService1Soap.ListarAsync
            Return MyBase.Channel.ListarAsync
        End Function
        
        Public Function Agregar( _
                    ByVal Ruc As String,  _
                    ByVal Nombre As String,  _
                    ByVal TipoDocumento As String,  _
                    ByVal Estado As String,  _
                    ByVal Condicion As String,  _
                    ByVal Direccion As String,  _
                    ByVal Ubigeo As String,  _
                    ByVal ViaTipo As String,  _
                    ByVal ViaNombre As String,  _
                    ByVal ZonaCodi As String,  _
                    ByVal ZonaTipo As String,  _
                    ByVal numero As String,  _
                    ByVal Interior As String,  _
                    ByVal Lote As String,  _
                    ByVal Dpto As String,  _
                    ByVal Manzana As String,  _
                    ByVal Kilometro As String,  _
                    ByVal Distrito As String,  _
                    ByVal Provincia As String,  _
                    ByVal Departamento As String) As Boolean Implements ServiceReference1.WebService1Soap.Agregar
            Return MyBase.Channel.Agregar(Ruc, Nombre, TipoDocumento, Estado, Condicion, Direccion, Ubigeo, ViaTipo, ViaNombre, ZonaCodi, ZonaTipo, numero, Interior, Lote, Dpto, Manzana, Kilometro, Distrito, Provincia, Departamento)
        End Function
        
        Public Function AgregarAsync( _
                    ByVal Ruc As String,  _
                    ByVal Nombre As String,  _
                    ByVal TipoDocumento As String,  _
                    ByVal Estado As String,  _
                    ByVal Condicion As String,  _
                    ByVal Direccion As String,  _
                    ByVal Ubigeo As String,  _
                    ByVal ViaTipo As String,  _
                    ByVal ViaNombre As String,  _
                    ByVal ZonaCodi As String,  _
                    ByVal ZonaTipo As String,  _
                    ByVal numero As String,  _
                    ByVal Interior As String,  _
                    ByVal Lote As String,  _
                    ByVal Dpto As String,  _
                    ByVal Manzana As String,  _
                    ByVal Kilometro As String,  _
                    ByVal Distrito As String,  _
                    ByVal Provincia As String,  _
                    ByVal Departamento As String) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceReference1.WebService1Soap.AgregarAsync
            Return MyBase.Channel.AgregarAsync(Ruc, Nombre, TipoDocumento, Estado, Condicion, Direccion, Ubigeo, ViaTipo, ViaNombre, ZonaCodi, ZonaTipo, numero, Interior, Lote, Dpto, Manzana, Kilometro, Distrito, Provincia, Departamento)
        End Function
        
        Public Function Buscar(ByVal texto As String, ByVal criterio As String) As System.Data.DataSet Implements ServiceReference1.WebService1Soap.Buscar
            Return MyBase.Channel.Buscar(texto, criterio)
        End Function
        
        Public Function BuscarAsync(ByVal texto As String, ByVal criterio As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.WebService1Soap.BuscarAsync
            Return MyBase.Channel.BuscarAsync(texto, criterio)
        End Function
    End Class
End Namespace
